### ISSUE TITLE
Where can I obtain the pre-trained model of ResNet trained with DCLS

### ISSUE THREAD

**Issue by GluttonK** [K-H-Ismail/Dilated-Convolution-with-Learnable-Spacings-PyTorch#3]
In your paper , I saw a result of ResNet50-dcls given besides the ConvNeXt-dcls. But I didn't find the trained model. If I need to train it by myself,Could you give the setting about it?Thank you

**Comment by K-H-Ismail** [comment]
Hello, 

Here is a link with the **best checkpoint for the two resnet-dcls runs** of the paper along with the **configs**, **summary** and **args** used at that time. We used [timm](https://github.com/huggingface/pytorch-image-models) and a light training config for resnet (A3-config described in [this paper](https://arxiv.org/pdf/2110.00476v1.pdf)).

[link to the checkpoints](https://zenodo.org/record/8373830)

Besides, this last checkpoints use the v0 version of DCLS that uses bilinear interpolation. We discovered that a better interpolation (Gaussian) could be used instead [please refer to this paper](https://arxiv.org/abs/2306.00817). We encourage you, if you want to do further investigations, to retrain using this last interpolation technique. More details are provided in this short blog post along with a script to replace all your convolutions with DCLS ones (see [medium story](https://medium.com/p/dea93c490a82)).

We abondonned the research on architectures that do not use depthwise separable convolutions because implementing a dialted kernel of size 7 and higher is prohibitive in time if we don't use  depthwise separable convolutions  along with depthwise implicit gemm method [link to the code of this method](https://github.com/MegEngine/cutlass/tree/master/examples/19_large_depthwise_conv2d_torch_extension) and [original paper](https://arxiv.org/abs/2203.06717). Maybe you could investigate ResNeXt or ConvNeXt (as we did in our paper) as they use depthwise separable convs.

**Comment by GluttonK** [comment]
Thank you very much， It helps a lot!!!

**Comment by K-H-Ismail** [comment]
You're welcome,

I'm closing this issue, but feel free to reopen it if you have any questions or comments.
